server:
  port: 8080

spring:
  application:
    name: heic-converter-ms
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

heic:
  convert-command: heif-convert
  timeout: 20s

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
